const LIMIT_CHAT_SELECTED = 25
const LIMIT_FRIEND_SELECTED = 25
const LIMIT_USER_SELECTED = 25
const LIMIT_CONSERVATION_SELECTED = 25

export {
  LIMIT_CHAT_SELECTED,
  LIMIT_FRIEND_SELECTED,
  LIMIT_USER_SELECTED,
  LIMIT_CONSERVATION_SELECTED,
}
